// 応答文をそのまま見る
import { mkdtempSync, rmSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execSync } from "node:child_process";
import { Board, Bus } from "./src/engine/board.js";
import { TaskBlackboard } from "./src/engine/tasks.js";
import { createTools } from "./src/engine/tools.js";
const GIT = (cmd, cwd) => execSync(cmd, { cwd, stdio: ["ignore", "pipe", "ignore"] }).toString();
const base = mkdtempSync(join(tmpdir(), "hive-d2-"));
const main = join(base, "main");
const ws = join(base, "wt");
mkdirSync(main, { recursive: true });
GIT("git init -q -b main", main);
GIT("git config user.email t@t && git config user.name t", main);
writeFileSync(join(main, "package.json"), '{"name":"x"}\n');
GIT("git add -A && git commit -qm init", main);
mkdirSync(ws, { recursive: true });
GIT(`git clone -q "${main}" "${ws}"`, base);
GIT("git config user.email w@t && git config user.name w", ws);
GIT("git checkout -q -b agent/alpha", ws);
writeFileSync(join(ws, "README.md"), "worker side\n");
GIT("git add -A && git commit -qm w1", ws);
writeFileSync(join(main, "README.md"), "main side\n");
GIT("git add -A && git commit -qm m1", main);
const bus = new Bus();
const tasks = new TaskBlackboard(ws, bus);
tasks.create({ id: "cw1", role: "impl", body: "work" });
const posted = [];
const board = { post(role, text) { posted.push(text); }, on() { return () => {}; } };
const approvals = { require: true, pending: new Map([["cw1", { agentId: "alpha", worktreePath: ws }]]), pickReviewer: () => null };
const tools = createTools({ agent: { id: "beta", role: "review", displayName: "b", personaText: "# b" }, workspace: ws, mainWorkspace: main, board, tasks, bus, approvals, modelPolicy: { escalationThreshold: 1, escalateModel: null } });
const c = await tools.execute("claim_next_task", {});
console.log("claim:", c.ok, String(c.text).slice(0, 80));
const t0 = Date.now();
const r = await tools.execute("finish_task", { task_id: "verify-cw1" });
console.log("elapsed", Date.now() - t0);
console.log("ok:", r.ok);
console.log("text:", String(r.text));
console.log("posted:", JSON.stringify(posted));
rmSync(base, { recursive: true, force: true });
