import { mkdtempSync, rmSync, mkdirSync, writeFileSync, readdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execSync } from "node:child_process";
import { Bus } from "./src/engine/board.js";
import { TaskBlackboard } from "./src/engine/tasks.js";
import { createTools } from "./src/engine/tools.js";
const base = mkdtempSync(join(tmpdir(), "probe7-"));
const main = join(base, "main"); const ws = join(base, "wt");
mkdirSync(main, { recursive: true });
execSync("git init -q -b main", { cwd: main, stdio: "ignore" });
execSync("git config user.email t@t && git config user.name t", { cwd: main, stdio: "ignore" });
writeFileSync(join(main, "package.json"), "{}\n");
execSync("git add -A && git commit -qm init", { cwd: main, stdio: "ignore" });
mkdirSync(ws, { recursive: true });
execSync("git clone -q \"" + main + "\" \"" + ws + "\"", { cwd: base, stdio: "ignore" });
const bus = new Bus();
const tasks = new TaskBlackboard(ws, bus);
const approvals = { require: true, pickReviewer() { return { id: "beta", role: "review" }; }, pending: new Map() };
const board = { post() {}, on() { return () => {}; } };
const created = tasks.create({ id: "cw1", role: "impl", body: "work" });
console.log("created:", created, "open:", readdirSync(join(ws, "tasks/open")));
const alpha = createTools({ agent: { id: "alpha", displayName: "a", role: "impl", personaText: "#a" }, workspace: ws, mainWorkspace: main, board, tasks, bus, approvals, modelPolicy: { escalationThreshold: 1, escalateModel: null } });
const c1 = await alpha.execute("claim_next_task", {});
console.log("c1:", c1.ok, String(c1.text).slice(0, 40));
rmSync(base, { recursive: true, force: true });
