// release応答のボディレベル確認(CLIのexit経由でなくAPI応答を直接見る)
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Bus } from "./src/engine/board.js";
import { startUi as _startUi } from "./src/ui/server.js";
import { startUiTokenized } from "./test/helpers/hf-token.js";
const ws = mkdtempSync(join(tmpdir(), "hive-rel-"));
const bus = new Bus();
const config = { workspace: ws, ui: { port: 0 }, model: { model: "test-model" }, agents: [] };
const ui = await startUiTokenized(_startUi, { config, modelFactory: () => ({}), bus, autoStart: false });
const port = config.ui.port, token = ui.token;
const post = (body) => fetch(`http://127.0.0.1:${port}/api/tasks`, { method: "POST", headers: { "content-type": "application/json", "x-hive-token": token, origin: "http://localhost" }, body: JSON.stringify(body) }).then(r => r.json());
await post({ action: "create", id: "cli-t2", body: "x" });
const rel = await post({ action: "release", id: "cli-t2" });
console.log("release応答:", JSON.stringify(rel));
const st = await fetch(`http://127.0.0.1:${port}/api/state`).then(r => r.json());
const t2 = (st.tasks ?? []).find(t => t.id === "cli-t2");
console.log("cli-t2状態:", JSON.stringify(t2));
ui.close(); rmSync(ws, { recursive: true, force: true }); process.exit(0);
