import { readFileSync } from "node:fs";
const NL = String.fromCharCode(10);
const src = readFileSync("test/test-triage.test.js", "utf8");
const m = src.match(/const REAL_SUMMARY_TAIL = \[([\s\S]*?)\]\.join\(NL\);/);
const arrSrc = m[1].replace(/BS \+/g, JSON.stringify(String.fromCharCode(92)) + " + ").replace(/NL/g, JSON.stringify(NL));
const FIXTURE = eval("[" + arrSrc + "]").join(NL);
const idx = FIXTURE.indexOf("failing tests:");
const section = FIXTURE.slice(idx);
const entryRe = /^test at (.+)$/gm;
const starts = [];
let mm;
while ((mm = entryRe.exec(section)) !== null) starts.push({ file: mm[1], at: mm.index + mm[0].length });
console.log("entries:", starts.length);
const last = starts[starts.length - 1];
const block = section.slice(last.at, section.indexOf("test at", last.at) >= 0 ? section.indexOf("test at", last.at) : undefined);
console.log("LAST BLOCK >>>");
console.log(JSON.stringify(block));
const errLine = block.match(/^\s{0,4}([A-Za-z_$][\w$]*(?:Error|Exception))(?:\s*\[[A-Z_]+\])?:?\s*(.*)$/m);
console.log("errLine:", errLine && JSON.stringify([errLine[1], errLine[2]]));
