import { startUi } from '../src/ui/server.js';
import { Bus } from '../src/engine/board.js';
import { PermissionGate } from '../src/engine/permissions.js';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const ws = mkdtempSync(join(tmpdir(), 'dbg-'));
const bus = new Bus();
const gate = new PermissionGate({ bus, askTimeoutSec: 2 });
const config = { workspace: ws, ui: { port: 0 }, model: { model: 'test' }, agents: [], budget: { maxTokensPerRun: 1 }, permissions: {} };
const ui = await startUi({ config, modelFactory: () => ({}), bus, autoStart: false });
const p = gate.check('git push origin main');
await new Promise((r) => setTimeout(r, 200));
const st = await fetch('http://127.0.0.1:' + config.ui.port + '/api/state').then((r) => r.json());
console.log('requests in /api/state:', JSON.stringify(st.live?.requests ?? null));
console.log('gate resolved:', JSON.stringify(await p));
process.exit(0);